#Problem 2 Even Fibonacci numbers
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
fib = [1,2]
i = 0
while fib[-1] < 4000000:
    fib.append(fib[i]+fib[i+1])
    i += 1
sums = 0
for n in fib:
    if n % 2 == 0:
        sums += n
print(sums)
